email.username=goldbyts@gmail.com
email.password=<secret>
email.from=danek
email.subject=Welcome to our service!
email.recipients=goldbyts@gmail.com
email.template=welcome.html
email.attachments=D:/Downloads/image.png,D:/Downloads/Certificate.pdf